### ISSUE TITLE
Live DJ takeover (audio only) doesn't update the metadata ticker

### ISSUE THREAD

**Issue by nullfunction** [seriousbears/seriousbears.github.io#5]
Chrome on Nexus 6, waited several minutes and no updates. Confirmed we're getting metadata through /stats as expected.

**Comment by nullfunction** [comment]
Seems that in addition to the above, the metadata never updates after it's initial load. I can confirm icecast changes metadata, maybe something is being cached?

**Comment by tylerstraub** [comment]
This has been replaced with an HTML5 webworker, poll time decreased to 15 seconds and resolved a bug with using the wrong jQuery method to replace text within a span.
